name: Flake Update

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch: {}

jobs:
  update-flake:
    runs-on: native
    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_READ_WRITE_TOKEN }}

      - name: Update flake.lock
        run: nix flake update

      - name: Check for changes
        id: diff
        run: |
          if git diff --quiet flake.lock; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and push
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name "[Au]@Copernicus"
          git config user.email "stelare-rose@noreply.git.starrytea.cc"
          git add flake.lock
          git commit -m "[Automated] Chore: Update flake.lock"
          git push
