# --- terminal & core ---
set-option -g status-position top
set -g base-index 1
setw -g pane-base-index 1
setw -g window-status-separator ""
set -g pane-border-status off
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -g default-terminal "xterm-256color"
set-option -sa terminal-features ',xterm-256color:RGB'
bind '`' send-keys '`'

# --- status bar ---
set -g status-style "bg=#decec1,fg=#3b3b3b"
set -g status-left-length 100
set -g status-right-length 100

# window tabs
set -g window-status-format         "#[fg=#f7f4e9,bg=#d4a266]  #I #W "
set -g window-status-current-format "#[fg=#f7f4e9,bg=#e3cd7f,bold]  #I #W "

# pane borders
set -g pane-border-style        "fg=#decec1"
set -g pane-active-border-style "fg=#9bb0de"

# message / command prompt
set -g message-style "bg=#e6d9c8,fg=#3b3b3b"

set -g status-left "#[fg=#f7f4e9 bg=#cf8282]  #(tmux display-message -p '#S' | sed 's/-[0-9]*$//') "
# right: application | cpu | session | uptime | battery
set -g status-right \
  "#[fg=#f7f4e9,bg=#9b98d6] 󰣖 #(tmux display-message -p '#W') #[fg=#f7f4e9,bg=#dbb4d3] 󰅐 #(uptime -p | sed 's/up //;s/ hours\{0,1\}/h/;s/ minutes\{0,1\}/m/;s/,//g')"
